apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
      - name: analysis
        image: udaychhina/analysis:latest
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: analysis
spec:
  selector:
    app: analysis
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
