apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      initContainers:
      # - name: wait-for-authentication
      #   image: busybox
      #   command: ["sh", "-c", "until nc -z authentication 5000; do echo waiting for authentication; sleep 5; done"]
      - name: wait-for-mysql
        image: busybox
        command: ["sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done"]
      containers:
      - name: collection
        image: udaychhina/collection:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: collection
spec:
  selector:
    app: collection
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
