apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-init-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./db/init.sql  # Update this with the full absolute path


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-init-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
