apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
      - name: results
        image: udaychhina/results:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: results
spec:
  selector:
    app: results
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
